(define (problem ariac_vlm)
  (:domain ariac_kitting)

  (:objects
    agv4 - agv
    init_agv1 init_agv2 init_agv3 init_agv4 - agv_destination
    agv4_1 agv4_2 agv4_3 agv4_4 - agv_slot
    bin1_1 bin1_2 bin1_3 bin1_4 bin1_5 bin1_6 bin1_7 bin1_8 bin1_9 bin2_1 bin2_2 bin2_3 bin2_4 bin2_5 bin2_6 bin2_7 bin2_8 bin2_9 bin5_1 bin5_2 bin5_3 bin5_4 bin5_5 bin5_6 bin5_7 bin5_8 bin5_9 bin6_1 bin6_2 bin6_3 bin6_4 bin6_5 bin6_6 bin6_7 bin6_8 bin6_9 - bin_slot
    gripper_station1 gripper_station2 - gripper_station
    floor_init - location
    MMB30H56 - order
    blue_pump_1 blue_pump_2 blue_pump_3 blue_pump_4 blue_pump_5 green_regulator_1 green_regulator_2 green_regulator_3 green_regulator_4 green_regulator_5 purple_sensor_1 purple_sensor_2 purple_sensor_3 purple_sensor_4 purple_sensor_5 red_battery_1 red_battery_2 red_battery_3 red_battery_4 red_battery_5 - part
    floor - robot
    tray_3 tray_5 tray_8 - tray
    slot1 slot3 slot4 - tray_slot
  )

  (:init
    (agv_at agv4 init_agv4)
    (agv_reach agv4 init_agv4)
    (agv_reach agv4 warehouse)
    (at_robot floor floor_init)
    (good blue_pump_1)
    (good blue_pump_2)
    (good blue_pump_3)
    (good blue_pump_4)
    (good blue_pump_5)
    (good green_regulator_1)
    (good green_regulator_2)
    (good green_regulator_3)
    (good green_regulator_4)
    (good green_regulator_5)
    (good purple_sensor_1)
    (good purple_sensor_2)
    (good purple_sensor_3)
    (good purple_sensor_4)
    (good purple_sensor_5)
    (good red_battery_1)
    (good red_battery_2)
    (good red_battery_3)
    (good red_battery_4)
    (good red_battery_5)
    (gripper_empty floor)
    (has_part_gripper floor)
    (home agv4 init_agv4)
    (order_needs_part MMB30H56 blue_pump_1 agv4_4)
    (order_needs_part MMB30H56 purple_sensor_1 agv4_1)
    (order_needs_part MMB30H56 red_battery_1 agv4_3)
    (order_needs_part MMB30H56 red_battery_2 agv4_2)
    (order_uses_tray MMB30H56 tray_5 agv4)
    (part_on blue_pump_1 bin5_1)
    (part_on blue_pump_2 bin5_3)
    (part_on blue_pump_3 bin5_5)
    (part_on blue_pump_4 bin5_7)
    (part_on blue_pump_5 bin5_9)
    (part_on green_regulator_1 bin6_1)
    (part_on green_regulator_2 bin6_3)
    (part_on green_regulator_3 bin6_5)
    (part_on green_regulator_4 bin6_7)
    (part_on green_regulator_5 bin6_9)
    (part_on purple_sensor_1 bin1_1)
    (part_on purple_sensor_2 bin1_3)
    (part_on purple_sensor_3 bin1_5)
    (part_on purple_sensor_4 bin1_7)
    (part_on purple_sensor_5 bin1_9)
    (part_on red_battery_1 bin2_1)
    (part_on red_battery_2 bin2_3)
    (part_on red_battery_3 bin2_5)
    (part_on red_battery_4 bin2_7)
    (part_on red_battery_5 bin2_9)
    (robot_reach agv4_1)
    (robot_reach agv4_2)
    (robot_reach agv4_3)
    (robot_reach agv4_4)
    (robot_reach bin1_1)
    (robot_reach bin1_2)
    (robot_reach bin1_3)
    (robot_reach bin1_4)
    (robot_reach bin1_5)
    (robot_reach bin1_6)
    (robot_reach bin1_7)
    (robot_reach bin1_8)
    (robot_reach bin1_9)
    (robot_reach bin2_1)
    (robot_reach bin2_2)
    (robot_reach bin2_3)
    (robot_reach bin2_4)
    (robot_reach bin2_5)
    (robot_reach bin2_6)
    (robot_reach bin2_7)
    (robot_reach bin2_8)
    (robot_reach bin2_9)
    (robot_reach bin5_1)
    (robot_reach bin5_2)
    (robot_reach bin5_3)
    (robot_reach bin5_4)
    (robot_reach bin5_5)
    (robot_reach bin5_6)
    (robot_reach bin5_7)
    (robot_reach bin5_8)
    (robot_reach bin5_9)
    (robot_reach bin6_1)
    (robot_reach bin6_2)
    (robot_reach bin6_3)
    (robot_reach bin6_4)
    (robot_reach bin6_5)
    (robot_reach bin6_6)
    (robot_reach bin6_7)
    (robot_reach bin6_8)
    (robot_reach bin6_9)
    (robot_reach floor_init)
    (robot_reach gripper_station1)
    (robot_reach gripper_station2)
    (robot_reach init_agv1)
    (robot_reach init_agv2)
    (robot_reach init_agv3)
    (robot_reach init_agv4)
    (robot_reach slot1)
    (robot_reach slot3)
    (robot_reach slot4)
    (slot_empty agv4_1)
    (slot_empty agv4_2)
    (slot_empty agv4_3)
    (slot_empty agv4_4)
    (slot_of agv4_1 agv4)
    (slot_of agv4_2 agv4)
    (slot_of agv4_3 agv4)
    (slot_of agv4_4 agv4)
    (tray_on_slot tray_3 slot1)
    (tray_on_slot tray_5 slot3)
    (tray_on_slot tray_8 slot4)
  )

  (:goal (and
    (submitted MMB30H56)
  ))
)
